id: P009328
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:33:42.288325
source_metadata:
  id: bdr:W3CN4774
  title: རྗེ་བཙུན་མི་ལའི་གསུང་མགུར་གཅེས་བསྡུས་ངེས་དོན་གདམས་ངག་རོལ་མཚོ།
  author: ''
  volumes:
    50f1efd0fb024d078befe422f0ab606b:
      image_group_id: I3CN4776
      title: ''
      volume_number: 1
      total_pages: 284
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
