id: IF36B8CC3
legacy_id: P009328
ocr_import_info:
  bdrc_scan_id: W3CN4774
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T18:57:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:41:45.050198+00:00'
last_modified: 2022-08-27 19:41:57.982006
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4774
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4774
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྗེ་བཙུན་མི་ལའི་གསུང་མགུར་གཅེས་བསྡུས་ངེས་དོན་གདམས་ངག་རོལ་མཚོ།
  author: རྗེ་བཙུན་མི་ལ་རས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.903935035030513
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN4776:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4776
      total_pages: 284
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4776.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.903935035030513
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
