id: IF36B8CC3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:58:52+00:00'
last_modified: '2022-06-08T10:14:15.696107+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4774
  title: རྗེ་བཙུན་མི་ལའི་གསུང་མགུར་གཅེས་བསྡུས་ངེས་དོན་གདམས་ངག་རོལ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    38B6:
      image_group_id: I3CN4776
      title: ''
      total_pages: 284
      order: 1
      base_file: 38B6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
